const cardsBag = [
  { cardLevel: 4, cardName: '克雷色利亞', cardImage: '' },
  { cardLevel: 3, cardName: '烈咬陸鯊', cardImage: '' },
  { cardLevel: 2, cardName: '地幔岩', cardImage: '' },
  { cardLevel: 2, cardName: '地幔岩', cardImage: '' },
  { cardLevel: 3, cardName: '烈焰猴', cardImage: '' },
  { cardLevel: 1, cardName: '小火焰猴', cardImage: '' },
  { cardLevel: 5, cardName: '固拉多', cardImage: 'horumon02.png' },
  { cardLevel: 2, cardName: '沼王', cardImage: 'horumon03.png' },
  { cardLevel: 2, cardName: '心蝙蝠', cardImage: '' },
  { cardLevel: 2, cardName: '心蝙蝠', cardImage: '' },
  { cardLevel: 2, cardName: '猛火猴', cardImage: '' },
  { cardLevel: 4, cardName: '龍捲雲', cardImage: '' },
  { cardLevel: 3, cardName: '龐岩怪', cardImage: '' },
  { cardLevel: 1, cardName: '草苗龜', cardImage: '' },
  { cardLevel: 1, cardName: '滾滾蝙蝠', cardImage: '' },
  { cardLevel: 2, cardName: '頓甲', cardImage: '' },
  { cardLevel: 1, cardName: '咕咕', cardImage: '' },
  { cardLevel: 2, cardName: '波皇子', cardImage: '' },
  { cardLevel: 1, cardName: '含羞苞', cardImage: '' },
  { cardLevel: 1, cardName: '圓陸鯊', cardImage: '' },
  { cardLevel: 4, cardName: '艾路雷朵', cardImage: '' },
  { cardLevel: 2, cardName: '貓頭夜鷹', cardImage: '' },
  { cardLevel: 4, cardName: '沙奈朵', cardImage: '' },
  { cardLevel: 1, cardName: '烏波', cardImage: '' },
  { cardLevel: 3, cardName: '心蝙蝠', cardImage: '' },
  { cardLevel: 2, cardName: '豪力', cardImage: '' },
  { cardLevel: 1, cardName: '拉魯拉絲', cardImage: '' },
  { cardLevel: 1, cardName: '草苗龜', cardImage: '' },
  { cardLevel: 3, cardName: '艾路雷朵', cardImage: '' },
  { cardLevel: 3, cardName: '暴鯉龍', cardImage: '' },
  { cardLevel: 4, cardName: '巨鉗螳螂', cardImage: '' },
  { cardLevel: 1, cardName: '烏波', cardImage: '' },
  { cardLevel: 4, cardName: '怪力', cardImage: '' },
  { cardLevel: 1, cardName: '腕力', cardImage: '' },
  { cardLevel: 1, cardName: '波加曼', cardImage: '' },
  { cardLevel: 3, cardName: '土台龜', cardImage: 'horumon04.png' },
  { cardLevel: 3, cardName: '怪力', cardImage: '' },
  { cardLevel: 2, cardName: '毒薔薇', cardImage: '' },
  { cardLevel: 3, cardName: '飛天螳螂', cardImage: '' },
  { cardLevel: 2, cardName: '頓甲', cardImage: '' },
  { cardLevel: 1, cardName: '拉魯拉絲', cardImage: '' },
  { cardLevel: 3, cardName: '怪力', cardImage: '' },
  { cardLevel: 1, cardName: '石丸子', cardImage: '' },
  { cardLevel: 2, cardName: '尖牙陸鯊', cardImage: '' },
  { cardLevel: 2, cardName: '貓頭夜鷹', cardImage: '' },
  { cardLevel: 4, cardName: '烈咬陸鯊', cardImage: '' },
  { cardLevel: 2, cardName: '樹林龜', cardImage: '' },
  { cardLevel: 5, cardName: '迷擬Q', cardImage: 'horumon01.png' },
  { cardLevel: 1, cardName: '小小象', cardImage: '' },
  { cardLevel: 2, cardName: '奇魯莉安', cardImage: '' },
]

const cardColor = [
  '#ff3000', '#ffe600', '#00c109', '#0035ba', '#4d09b7'
]

export {
  cardsBag,
  cardColor,
}